/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abschluss;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniel
 */
public class Doz1 extends javax.swing.JFrame {

    /**
     * Creates new form Doz1
     */
    public Doz1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        tf_nachname = new javax.swing.JTextField();
        tf_titel = new javax.swing.JTextField();
        tf_tc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_dozentlist = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_mesaj = new javax.swing.JTextArea();
        checkButton = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Nachname");

        jLabel3.setText("Titel");

        jLabel4.setText("TC");

        table_dozentlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Nachname", "Titel", "TC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_dozentlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_dozentlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_dozentlist);

        saveButton.setText("Hinzufugen");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Aktualisieren");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Loschen");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        ta_mesaj.setEditable(false);
        ta_mesaj.setBackground(new java.awt.Color(240, 240, 240));
        ta_mesaj.setColumns(20);
        ta_mesaj.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        ta_mesaj.setLineWrap(true);
        ta_mesaj.setRows(5);
        jScrollPane2.setViewportView(ta_mesaj);

        checkButton.setText("Zum sehen alles in Table, dadurch es kann  loschen und aktualisieren.");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(deleteButton)
                                .addGap(61, 61, 61)
                                .addComponent(updateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(saveButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(170, 170, 170)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_name)
                                    .addComponent(tf_nachname)
                                    .addComponent(tf_titel)
                                    .addComponent(tf_tc))))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_titel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String n= tf_name.getText();
        String nn= tf_nachname.getText();
        String title= tf_titel.getText();
        String tc= tf_tc.getText();
        Dozent d= new Dozent(n,nn,title,tc);
        if(d.tckontrol(tc) && !uni.getDozentlist().toString().contains(tc) && !tf_name.getText().isEmpty() 
                && !tf_nachname.getText().isEmpty() ) {
        uni.getDozentlist().add(d);
        ta_mesaj.setText("Dozent eklenmistir " + uni.getDozentlist().size()+ " kadar dozent mevcut");
        String[] ss= new String[4];
        ss[0]= n;
        ss[1]= nn;
        ss[2]= title;
        ss[3]= tc;
        DefaultTableModel dtm= (DefaultTableModel) table_dozentlist.getModel();
        dtm.addRow(ss);
        }
        else {
        ta_mesaj.setText("TC ist falsch oder vorher gegebenes, \nName und Nachname soll nicht leer.");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        int i= table_dozentlist.getSelectedRow();
        if (i>=0 ) {
            Dozent d= uni.getDozentlist().get(i);
            if (d.tckontrol(tf_tc.getText()) && !tf_name.getText().isEmpty() && !tf_nachname.getText().isEmpty() 
                    && !uni.getDozentlist().toString().contains(tf_tc.getText())) {
            d.setName(tf_name.getText());
            d.setNachname(tf_nachname.getText());
            d.setTitel(tf_titel.getText());
            d.setTcno(tf_tc.getText());
            table_dozentlist.getModel().setValueAt(d.getName(), i, 0);
            table_dozentlist.getModel().setValueAt(d.getNachname(), i, 1);
            table_dozentlist.getModel().setValueAt(d.getTitel(), i, 2);  
            table_dozentlist.getModel().setValueAt(d.getTcno(), i, 3); 
            }
            else{
            ta_mesaj.setText("TC  ist falsch oder vorher gegebenes ");
            }
        }
        if ((i>=0 ) && (uni.getDozentlist().toString().contains(tf_tc.getText())) && !tf_name.getText().isEmpty() 
                && !tf_nachname.getText().isEmpty()){
            Dozent d= uni.getDozentlist().get(i);
            d.setName(tf_name.getText());
            d.setNachname(tf_nachname.getText());
            d.setTitel(tf_titel.getText());
            table_dozentlist.getModel().setValueAt(d.getName(), i, 0);
            table_dozentlist.getModel().setValueAt(d.getNachname(), i, 1);
            table_dozentlist.getModel().setValueAt(d.getTitel(), i, 2);  
            table_dozentlist.getModel().setValueAt(d.getTcno(), i, 3);  
            ta_mesaj.setText("");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void table_dozentlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dozentlistMouseClicked
        int i= table_dozentlist.getSelectedRow();
        if (i>=0) {
        tf_name.setText((String) table_dozentlist.getModel().getValueAt(i, 0));
        tf_nachname.setText((String) table_dozentlist.getModel().getValueAt(i, 1));
        tf_titel.setText((String) table_dozentlist.getModel().getValueAt(i, 2));
        tf_tc.setText((String) table_dozentlist.getModel().getValueAt(i, 3));
        }
    }//GEN-LAST:event_table_dozentlistMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int i= table_dozentlist.getSelectedRow();
        if (i>=0 ) {
        uni.getDozentlist().remove(i);
        DefaultTableModel dtm= (DefaultTableModel) table_dozentlist.getModel();
        dtm.removeRow(i);
        ta_mesaj.setText("Dozent silinmistir " + uni.getDozentlist().size()+ " kadar dozent mevcut");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed
    
    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
          DefaultTableModel dtm= (DefaultTableModel) table_dozentlist.getModel();
          dtm.setRowCount(0);
        for (int i = 0; i < uni.getDozentlist().size(); i++) {
            String[] ss= new String[4];
            ss[0]= uni.getDozentlist().get(i).getName();
            ss[1]= uni.getDozentlist().get(i).getNachname();
            ss[2]= uni.getDozentlist().get(i).getTitel();
            ss[3]= uni.getDozentlist().get(i).getTcno();
            dtm.addRow(ss);
            }
    }//GEN-LAST:event_checkButtonActionPerformed
    
    Universitaet uni= new Universitaet();                    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextArea ta_mesaj;
    private javax.swing.JTable table_dozentlist;
    private javax.swing.JTextField tf_nachname;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_tc;
    private javax.swing.JTextField tf_titel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}

