/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abschluss;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniel
 */
public class Lva3 extends javax.swing.JFrame {

    /**
     * Creates new form Lva3
     */
    public Lva3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_derskodu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_auflisten = new javax.swing.JTable();
        ogrencigoster = new javax.swing.JButton();
        dozentgoster = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_mesaj = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ders Kodu");

        ta_auflisten.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ta_auflisten);

        ogrencigoster.setText("Kayıtlı ogrencileri goster");
        ogrencigoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrencigosterActionPerformed(evt);
            }
        });

        dozentgoster.setText("Kayıtlı dozentleri goster");
        dozentgoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dozentgosterActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        ta_mesaj.setBackground(new java.awt.Color(240, 240, 240));
        ta_mesaj.setColumns(20);
        ta_mesaj.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        ta_mesaj.setRows(5);
        jScrollPane2.setViewportView(ta_mesaj);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dozentgoster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(ogrencigoster)))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_derskodu, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_derskodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ogrencigoster)
                    .addComponent(dozentgoster))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ogrencigosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrencigosterActionPerformed
        String kod= tf_derskodu.getText();
        ta_mesaj.setText("");
        DefaultTableModel dtm= (DefaultTableModel) ta_auflisten.getModel();
        dtm.setRowCount(0);
        if(uni.getLvalist().toString().contains(kod)) {
          ta_mesaj.setText("0 kisi mevcut"); //eger ders mevcutsa ama kimse yoksa donutsuz kalmamasi icin buraya koydum
          for(int i=0; i< uni.getLvawithstudent().size(); i++){
            if(uni.getLvawithstudent().get(i).getDers().equals(kod)){
                String idnumarası= uni.getLvawithstudent().get(i).getId();
                for(int j=0; j< uni.getStudentlist().size(); j++){
                    if(uni.getStudentlist().get(j).getId().equals(idnumarası)) {
                    String[] ss= new String[5];
                    ss[0]= uni.getStudentlist().get(j).getName();
                    ss[1]= uni.getStudentlist().get(j).getNachname();
                    ss[2]= uni.getStudentlist().get(j).getId();
                    ss[3]= uni.getStudentlist().get(j).getFakultaet();
                    ss[4]= uni.getStudentlist().get(j).getProgramm();
                    dtm.addRow(ss);
                    ta_mesaj.setText(dtm.getRowCount() + " kisi mevcut");
                    }
                  }
              }
           }
          }
        else {ta_mesaj.setText("Eslesen ders bulunamadi");
        }
    }//GEN-LAST:event_ogrencigosterActionPerformed

    private void dozentgosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dozentgosterActionPerformed
          String kod= tf_derskodu.getText();
          ta_mesaj.setText("");
        DefaultTableModel dtm= (DefaultTableModel) ta_auflisten.getModel();
        dtm.setRowCount(0);
        if(uni.getLvalist().toString().contains(kod)) {
           ta_mesaj.setText("0 kisi mevcut"); //eger ders mevcutsa ama kimse yoksa donutsuz kalmamasi icin buraya koydum
          for(int i=0; i< uni.getLvawithdozent().size(); i++){
            if(uni.getLvawithdozent().get(i).getDers().equals(kod)){
                String tcnumarası= uni.getLvawithdozent().get(i).getTcno();
                for(int j=0; j< uni.getDozentlist().size(); j++){
                    if(uni.getDozentlist().get(j).getTcno().equals(tcnumarası)) {
                    String[] ss= new String[4];
                    ss[0]= uni.getDozentlist().get(j).getName();
                    ss[1]= uni.getDozentlist().get(j).getNachname();
                    ss[2]= uni.getDozentlist().get(j).getTitel();
                    ss[3]= uni.getDozentlist().get(j).getTcno();
                    dtm.addRow(ss);
                    ta_mesaj.setText(dtm.getRowCount() + " kisi mevcut");
                    }
                  }
              }
           }
          }
        else {
           ta_mesaj.setText("Eslesen ders bulunamadi"); 
        }    
    }//GEN-LAST:event_dozentgosterActionPerformed

    Universitaet uni= new Universitaet();
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lva3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lva3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lva3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lva3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lva3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dozentgoster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton ogrencigoster;
    private javax.swing.JTable ta_auflisten;
    private javax.swing.JTextArea ta_mesaj;
    private javax.swing.JTextField tf_derskodu;
    // End of variables declaration//GEN-END:variables
}
